apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: r5k20dzkf-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/r5k20dzkf-java-springboot-gitops